### ISSUE TITLE
Pie menus does not support multiple presets with the same name stored in different locations

### ISSUE THREAD

**Issue by manicpixelgirl** [wojtryb/Shortcut-Composer#66] opened 2023-10-06 04:39 UTC
- Plugin version: ... [v1.4.0]
- Operating System: ... [Win11]

Describe the issue you encounter.
- Pie menu doesn't recognize custom adjusted brushes from brush editor after install. I've attempted disabling/enabling script again but I still can't find my brush under the tags. 
- tried manual and tag mode in pie editor

**Comment by wojtryb** [comment] 2023-10-06 06:38
I can't reproduce that - you have to be more specific what are the steps to get this issue.

Newly created brushes added to tags are visible in the pie settings. Brush icons are not updated before krita restart - if that is your issue, than I'm afraid I will not fix it - it drastically increases plugin performance.

**Comment by wojtryb** [comment] 2023-10-06 08:01
Well, it's pretty weird, as it looks like some of the custom brushes are detected and some are not.

Is there some pattern behind those brushes that were not detected? What are their names? Do they use some special characters? Do they come from some specific brush pack? Were they created with some old version of krita long time ago? Do they use some specific brushtips?

There must be something behind those brushes that make them not load.

**Comment by wojtryb** [comment] 2023-10-06 08:41
Ok, so the problem is not missing brushes - they are available but under their original icons?

I can confirm that the preset from original Krita 4 library, after being overwritten is not properly displayed, but krita seems to be some problems in that situation.

To avoid that, you can save this brush under a different name and assign it to the "Erasers" tag. I think this is a bug in krita, which I won't be able to fix.

**Comment by wojtryb** [comment] 2023-10-06 08:50
All right, I think this is a bug in the plugin.

It looks like krita allows to save a preset under the same name multiple times - but only if you save it in different location - you can get that by saving default brush on your local machine. When there are two presets with the same name, my plugin will only store the second one.

I'll try to fix that, but you can consider using different names for your custom brushes to prevent things like that - overwriting custom brushes does not seem as the best practice.

**Comment by wojtryb** [comment] 2023-11-09 15:04
Hi, I made some research, and it looks like the problem is not fixable.

Krita has a rather serious design flaw here - it allows to have multiple presets of the same name, but in Python API returns them mapped to their names - as if they are guaranteed unique.

You simply cannot fetch more than one preset then.

**Closed by wojtryb** 2023-11-09 15:04 UTC
Labels: bug
