### ISSUE TITLE
Error loading plugin

### ISSUE THREAD

**Issue by Izaird** [wojtryb/Shortcut-Composer#43] opened 2023-05-03 00:52 UTC
**General info**
- Plugin version:  v1.2.2
- Operating System: Arch linux
- Python version: v3.11.3

**Bug description**
I was trying to use the plugin as usual but it didn't seem to work I launch the app from the terminal and give me this 

/usr/lib/krita-python-libs/krita added to PYTHONPATH
krita.scripting: "Traceback (most recent call last):"
krita.scripting: "  File \"/home/izaird/.local/share/krita/pykrita/shortcut_composer/__init__.py\", line 17, in <module>"
krita.scripting: "    from .shortcut_composer import ShortcutComposer"
krita.scripting: "  File \"/home/izaird/.local/share/krita/pykrita/shortcut_composer/shortcut_composer.py\", line 10, in <module>"
krita.scripting: "    from actions import create_actions"
krita.scripting: "  File \"/home/izaird/.local/share/krita/pykrita/shortcut_composer/actions.py\", line 12, in <module>"
krita.scripting: "    import templates"
krita.scripting: "  File \"/home/izaird/.local/share/krita/pykrita/shortcut_composer/templates/__init__.py\", line 21, in <module>"
krita.scripting: "    from .multiple_assignment import MultipleAssignment"
krita.scripting: "  File \"/home/izaird/.local/share/krita/pykrita/shortcut_composer/templates/multiple_assignment.py\", line 7, in <module>"
krita.scripting: "    from core_components import Controller, Instruction"
krita.scripting: "  File \"/home/izaird/.local/share/krita/pykrita/shortcut_composer/core_components/__init__.py\", line 14, in <module>"
krita.scripting: "    from .controller_base import Controller"
krita.scripting: "  File \"/home/izaird/.local/share/krita/pykrita/shortcut_composer/core_components/controller_base.py\", line 6, in <module>"
krita.scripting: "    from api_krita.pyqt import Text"
krita.scripting: "  File \"/home/izaird/.local/share/krita/pykrita/shortcut_composer/api_krita/pyqt/__init__.py\", l
ine 12, in <module>"
krita.scripting: "    from .text import Text"
krita.scripting: "  File \"/home/izaird/.local/share/krita/pykrita/shortcut_composer/api_krita/pyqt/text.py\", line 8, in <module>"
krita.scripting: "    @dataclass"
krita.scripting: "     ^^^^^^^^^"
krita.scripting: "  File \"/usr/lib/python3.11/dataclasses.py\", line 1223, in dataclass"
krita.scripting: "    return wrap(cls)"
krita.scripting: "           ^^^^^^^^^"
krita.scripting: "  File \"/usr/lib/python3.11/dataclasses.py\", line 1213, in wrap"
krita.scripting: "    return _process_class(cls, init, repr, eq, order, unsafe_hash,"
krita.scripting: "           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
krita.scripting: "  File \"/usr/lib/python3.11/dataclasses.py\", line 958, in _process_class"
krita.scripting: "    cls_fields.append(_get_field(cls
, name, type, kw_only))"
krita.scripting: "                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
krita.scripting: "  File \"/usr/lib/python3.11/dataclasses.py\", line 815, in _get_field"
krita.scripting: "    raise ValueError(f'mutable default {type(f.default)} for field '"
krita.scripting: "ValueError: mutable default <class 'PyQt5.QtGui.QColor'> for field color is not allowed: use default_factory"
krita.scripting: "Could not import shortcut_composer"
krita.scripting: Error loading plugin "shortcut_composer"

**Comment by wojtryb** [comment] 2023-05-03 10:21
Hi, thank you for reporting.

On Linux the only officially supported version of Krita is .appimage, which ships with all required dependencies. Running the plugin on Krita installed from Snap or distribution repositories is not recommended as it may not work out of the box and may require extra dependency-related work. (I assume you're not using appimage, as the plugins runs on python 3.11 and not 3.8 shipped with krita.)

The crash happened as either python 3.11 is more picky, or your version of Qt is so newer than expected and it broke backwards compatibility. As the issue is trivial I fixed that to make the plugin more future-proof, so if you want to keep using krita in this version you can download and reinstall the plugin in [this development version](https://github.com/wojtryb/Shortcut-Composer/tree/bugfix/mutable-qcolor).

The fix covers only this particular problem, and I can't guarantee there aren't more things like this, and the plugin will work on your setup.

**Comment by wojtryb** [comment] 2023-05-05 12:40
Merged bugfix to https://github.com/wojtryb/Shortcut-Composer/tree/development

**Closed by wojtryb** 2023-05-05 12:40 UTC
Labels: bug

**Comment by JoseConseco** [comment] 2023-06-21 11:29
I tried the dev version, on my arch linux, krita . And the previus issue is fixed, but I get  new one: 
NOT COOL: Duplicated action name from xml data:  "Transform tool: mesh"
libpng warning: zTXt: truncated
Could not load the resource from the bundle "paintoppresets" "paintoppresets/rst) Leather.kpp" "/home/bartosz/.local/share/krita/Rakurri_Brush_Set_V2.0.bundle"
krita.general: ERROR: unable to decode abr format version  23364 (subver  0 )
krita.general: ERROR: unable to decode abr format version  10 (subver  0 )
QObject::startTimer: Timers cannot have negative intervals
/usr/lib/krita-python-libs/krita added to PYTHONPATH
krita.scripting: "Traceback (most recent call last):"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/__init__.py\", line 17, in <module>"
krita.scripting: "    from .shortcut_composer import ShortcutComposer"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/shortcut_composer.py\", line 8, in <module>"
krita.scripting: "    from api_krita import Krita, Extension  # type: ignore"
krita.scripting: "    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/api_krita/__init__.py\", line 16, in <module>"
krita.scripting: "    from .core_api import KritaInstance"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/api_krita/core_api.py\", line 15, in <module>"
krita.scripting: "    from .wrappers import ("
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/api_krita/wrappers/__init__.py\", line 10, in <module>"
krita.scripting: "    from .tool_descriptor import ToolDescriptor"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/api_krita/wrappers/tool_descriptor.py\", line 7, in <module>"
krita.scripting: "    from ..enums import Tool"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/api_krita/enums/__init__.py\", line 7, in <module>"
krita.scripting: "    from .blending_mode import BlendingMode"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/api_krita/enums/blending_mode.py\", line 4, in <module>"
krita.scripting: "    from .helpers import EnumGroup, Group"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/api_krita/enums/helpers/__init__.py\", line 1, in <module>"
krita.scripting: "    from .enum_group import EnumGroup, Group"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/api_krita/enums/helpers/enum_group.py\", line 103, in <module>"
krita.scripting: "    class Edible(EnumGroup):"
krita.scripting: "  File \"/home/bartosz/.local/share/krita/pykrita/shortcut_composer/api_krita/enums/helpers/enum_group.py\", line 36, in __new__"
krita.scripting: "    attrs._member_names.remove(group_variable_name)"
krita.scripting: "    ^^^^^^^^^^^^^^^^^^^^^^^^^^"
krita.scripting: "AttributeError: 'dict' object has no attribute 'remove'"
krita.scripting: "Could not import shortcut_composer"
krita.scripting: Error loading plugin "shortcut_composer"
profileForCsIdWithFallbackImpl couldn't fetch a fallback profile for

I guess I should switch to appimage version .

**Comment by wojtryb** [comment] 2023-06-21 19:36
@JoseConseco appimage is only linux version I support. Please try it first.

Also please create a new issue for each new error. Yours is unrelated to the original one, and the original person will receive emails for new messages in this thread.
