### ISSUE TITLE
Pie menus move away from mouse pointer while adding actions on 4k screen

### ISSUE THREAD

**Issue by Dynline** [wojtryb/Shortcut-Composer#72] opened 2023-11-08 12:58 UTC
**General info**
- Plugin version: v1.4.1
- Operating System: windows 10
- huion kamvas 4k

**Bug description**
While on the huion 4k screen dragging and dropping values on the action pie menus causes the ring to "flee" from your mouse pointer and move toward the bottom of the screen. You may be able to add new things if you are fast enough. It works without problems if I move krita into my second screen with normal hd resolution and swap the actions there.

**Comment by wojtryb** [comment] 2023-11-09 14:52
Duplicate of #51

This is related to display scaling. I'm not sure this is really fixable, as it could be a bug in Qt, but I want to make some changes to related part of code to fix another issue - you can check out if it makes any difference: [download plugin with proposed changes](https://github.com/wojtryb/Shortcut-Composer/archive/refs/heads/1-4-2-fixup-proposal.zip)

**Comment by Dynline** [comment] 2023-11-11 17:45
Sorry for the late answer, I just had the time to try the new changes.

Adding and reordering works without any issue now!
Thank you!

**Comment by wojtryb** [comment] 2023-11-12 11:50
I'm glad it worked out!

I've released this and other fixes as [1.4.2](https://github.com/wojtryb/Shortcut-Composer/releases/tag/v1.4.2). Please update your plugin from the development version

**Closed by wojtryb** 2023-11-12 11:50 UTC
Labels: bug
